replicaCount: 2

image:
  repository: myimage
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

# ingress:
#   enabled: true
#   className: "nginx"
#   annotations:
#     kubernetes.io/ingress.class: "nginx"
#   hosts:
#     - host: hello-world.aks.example.com
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#   tls:
#     - secretName: hello-world-tls
#       hosts:
#         - hello-world.aks.example.com