apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap"
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>GAL</title></head>
    <body><h1>Hello, 2bcloud (:</h1></body>
    </html>
