apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: application-hpa
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: pod
        value: 1
      selectPolicy: Max
      stabilizationWindowSeconds: 60
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: po
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 10
